### ISSUE TITLE
Too dumb to understand the instructions

### ISSUE THREAD

**Issue by psociety** [shivpatel/bitwarden_rs_dropbox_backup#11]
Right on start it says  `It's highly recommend you run via the docker-compose.yml provided.` but then the initial setup instructions say `docker run -it <...>`.

So how exactly i have to set it up?
Should i : 
1. Add the new service in my existing ``docker-compose.yml`
2. Do `docker-compose up -d --no-deps --build bitwarden_dropbox_backup` to build the container
3. Do `docker run -it bitwarden_dropbox_backup` i guess? Or since i built the service i have to enter the shell like `docker-compose exec bitwarden_dropbox_backup sh`?
Also, isn't it recommended on the `yml` to have `container_name` set so it doesn't generate a random one?

**Comment by amakerlife** [comment]
Do you know how to set it up now?

**Comment by tetreum** [comment]
I went for another better documented solution:
```yml
  bw_backup:
     image: bruceforce/bw_backup
     container_name: bw_backup
     restart: unless-stopped
     depends_on:
        - vaultwarden
     volumes:
        - /YOUR_LOCAL_VAULT_FOLDER/:/data/
        - /YOUR_LOCAL_FOLDER_FOR_THE_BACKUP/:/backup_folder/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
     environment:
        - DB_FILE=/data/db.sqlite3
        - BACKUP_FILE=/backup_folder/bw_backup.sqlite3
           # EVERY DAY 5am
        - CRON_TIME=0 5 * * *
        - TIMESTAMP=false
        - UID=0
        - GID=0
```
